### ISSUE TITLE
Announcement en-GB User Interface Text Working Group

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#10]
All,

I am pleased to announce the following with Brian Teeman leading this overdue and needed core en-GB standardisation.

The PLT have accepted the proposal to review and standardise all the en-GB language strings in the core of Joomla based on the style guide that you can see [here](https://github.com/joomla/user-interface-text/) (until it gets a permanent home).

### Abstract
* The official language of Joomla is en-GB and yet the actual strings we use have been created, over 10 years, mainly by people who are not native en-GB speakers. 
* Create a style guide to standardise the correct usage of en-GB and assist anyone writing language strings for Joomla.
* A secondary aim is that this style guide can be used as a basis for translation teams.
* Traditional rules of grammar do not always apply to the web. See [Break Grammar Rules on Websites for Clarity](http://www.nngroup.com/articles/break-grammar-rules/)

#### Purpose
* Establish official style guidelines for writing en-GB strings.
* Ensure consistency throughout Joomla.
* Provide translation teams with an easy framework and guidelines to create their own style guides.	
* See [NNG on American vs British english for the web](http://www.nngroup.com/articles/american-vs-british-english-for-web/)
* The style guide is a living document that may be updated and added to over time as the need arises. 
* The style guide will be maintained by native en-GB speakers.

##### Stage 1
1. Consistency
2. Punctuation
3. Words to watch
4. Capitalisation

Nothing in Stage 1 will effect Translation Teams

##### Stage 2
1. Tooltips
2. Module and plugin descriptions
3. Manager
4. Action or Description

There may be items in Stage 2 that will effect Translation Teams

##### Stage 3 
1. Create a home for the style guide
2. Create ability for TT to fork the style guide and host centrally
3. Formulate a process for en-GB team to review any new or changed string before it is committed to core.

##### Stage 4
1. Promote style guide to extension and template developers to encourage them to adopt it.

### One Style to Rule the World 

![b42z9ugiqaalgl4](https://cloud.githubusercontent.com/assets/1296369/5604100/8ac21aee-939e-11e4-83e9-bad454afae72.jpg)

Thanks to those already involved and their hard work towards bringing about these changes.

**Comment by Hutchy68** [comment]
The announcement looks great Brian! Thanks for all your hard work on this initiative.

**Comment by brianteeman** [comment]
Over to you to post it wherever appropriate

**Comment by Hutchy68** [comment]
Ok, will do!

**Comment by Hutchy68** [comment]
I'm ready to push some buttons this morning. Email and blog post. If you are ok with the added text:

At the lead in ("All" will be removed in blog post)
>All,
>
>I am pleased to announce the following with Brian Teeman leading this overdue and needed core en-GB standardisation.

At the bottom
>Thanks to those already involved and their hard work towards bringing about these changes.

**Comment by brianteeman** [comment]
The picture is a joke - I am not sure its goof to use ;)

First PR is ready just want to wait till tonight when I get off the train and back to a fast internet
