### ISSUE TITLE
Viewlevel Access - Consistency Check

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#11]
General english issue

In most places column heading are "Access" but in the Module Assignment tab it is "View level"

In the User Manager itself we use "Access Level" and "Viewing Access Level"

**Comment by Hils** [comment]
Would it be two different situations? Access level lets a visitor do something whilst view level lets a visitor just look!

**Comment by Hutchy68** [comment]
Access could be both uses. Access level allows a visitor "to do" or "to view" something. Access level to do this or that. Access level to view this or that.

**Comment by Hils** [comment]
fair enough! I don't know all the contexts.

**Comment by brianteeman** [comment]
They are the same thing in the same situation just labelled differently in
the different screens

On 5 January 2015 at 18:39, Hils <notifications@github.com> wrote:

> fair enough! I don't know all the contexts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/11#issuecomment-68753707>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hils** [comment]
my vote is for access then because view suggests view only.

**Comment by brianteeman** [comment]
Thats the problem Hils. Access levels are VIEW only in fact their full name is Viewing Access Levels. The issue here is that 99% of the screens say Access but this one screen says View levels. Maybe these screenshots help to explain

![i0ue](https://cloud.githubusercontent.com/assets/1296369/5618235/d79ffe14-950e-11e4-9859-f47d0a80472f.png)


![zdlt](https://cloud.githubusercontent.com/assets/1296369/5618244/efa4c9ae-950e-11e4-8019-4056e5853794.png)

**Comment by chrisdavenport** [comment]
This is a frequent source of confusion.  How about we call them "view levels" and "access levels"?  Although "view levels" aren't actually "levels" at all, so maybe "view groups" or "viewing groups"?  Dunno, that's a tough one.

**Comment by hdouglassmith** [comment]
I think Chris is heading in the right direction here, "Access level" or "Access" can suggest ability beyond viewing therefore I would support including View or Viewing into the term or 'Read' as an alternative (Read only) tends to be understood as view only access.

Looking at the module manager example, part of the confusion (IMHO) is that "View level" is defining the minimum level to access (read) the item, perhaps including "Minimum" or "Lowest" so it become "Min View Level" or "Min level to view", starting to get a bit clunky though

**Comment by brianteeman** [comment]
@chrisdavenport what is the difference between view levels" and "access levels"? 

@hdouglassmith look at the article manager. the data in the column is the same but it is labelled access not view

As far as I can see there is NO difference and the full name is "viewing access levels" and its just that we abbreviated it to "access levels" or "access" in all the places that existed before real ACL and it is only in the new area of Menu Module Assignments that has the different "view level"

**Comment by chrisdavenport** [comment]
Access levels are the hierarchical levels that determine what a user can do (eg. configure, create, update, delete and other tasks including custom ones).  "Viewing access levels" only determine what a user can see.

A user can belong to one or more user groups and one or more user groups can be assigned to a "viewing access level" (although it's really a group rather than a level, because the "levels" don't form a hierarchy).  User groups can also be assigned "access level" permissions (which do form a hierarchy since the permissions follow the user group hierarchy).

So, you can change the "view level" of an article, say, by going into the article screen in the Article Manager and changing the "Access" drop-down on the right-hand side.  That determines which user groups can see the article.  You change the "access level" for articles by going into Article Manager -> Options -> Permissions where you can assign "Actions" to different user groups.  That determines which user groups can do things such as create or delete articles.  So "view levels" and "access levels" are quite distinct, although they are tied together by user groups.

Confused yet?

**Comment by brianteeman** [comment]
Yes very confused

I understand the difference between groups and levels. This column labelled
"view level" is displaying levels not groups as is the column everywhere
else that is called "access"

How does any of  this explain
administrator/index.php?option=com_users&view=levels which is called both
Viewing Access Levels and Access Levels

I just dont see why this column is labelled differently. To me it looks
like the full name is "Viewing Access Levels" which is normally shortened
to "Access Levels" or "access" but in this case has been shortened to "view
levels"

On 5 January 2015 at 22:50, Chris Davenport <notifications@github.com>
wrote:

> Access levels are the hierarchical levels that determine what a user can
> do (eg. configure, create, update, delete and other tasks including custom
> ones). "Viewing access levels" only determine what a user can see.
>
> A user can belong to one or more user groups and one or more user groups
> can be assigned to a "viewing access level" (although it's really a group
> rather than a level, because the "levels" don't form a hierarchy). User
> groups can also be assigned "access level" permissions (which do form a
> hierarchy since the permissions follow the user group hierarchy).
>
> So, you can change the "view level" of an article, say, by going into the
> article screen in the Article Manager and changing the "Access" drop-down
> on the right-hand side. That determines which user groups can see the
> article. You change the "access level" for articles by going into Article
> Manager -> Options -> Permissions where you can assign "Actions" to
> different user groups. That determines which user groups can do things such
> as create or delete articles. So "view levels" and "access levels" are
> quite distinct, although they are tied together by user groups.
>
> Confused yet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/11#issuecomment-68796604>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
What about:
Accessible by
and
Viewable by
?

**Comment by sanderpotjer** [comment]
ACL/Access Levels naming is very confusing right now, so first a thank you for looking into this.

In general I explain that the Joomla "Access Levels" are all about the View "action" of the Joomla ACL system. I used several times a language override for the "Access" label to make this more clear and changed it in the Dutch equivalent of "Visible for", if you have clear descriptive names of your Viewing Access Levels (and not something like "Special", who the heck is special?!) it makes sense. In that case you set an article "Visible for": "Any site visitor"/"Logged in users"/"Webmasters" as an example.

So yes, I would love to see a better label for this. Access seems to confuse people with "editing access", this might be a language thing too. In my opinion a label that clearly describes it is only about "Viewing" would be welcome.

**Comment by brianteeman** [comment]
Thanks Sander

@all
What I propose is this -
1. In the Stage 1 PR I change this one screen to use Access instead of View
Levels. This gets all the screens consistent

2. In Stage 2 we can create a specific PR that attempts to come up with a
better naming convention for this throughout joomla. Stage 2 PR are single
PRs for specific issues that might effect TT and docs and would be more
open for generic community review as they are global changes and not just
en-GB changes

Any objections?


On 6 January 2015 at 07:27, Sander Potjer <notifications@github.com> wrote:

> ACL/Access Levels naming is very confusing right now, so first a thank you
> for looking into this.
>
> In general I explain that the Joomla "Access Levels" are all about the
> View "action" of the Joomla ACL system. I used several times a language
> override for the "Access" label to make this more clear and changed it in
> the Dutch equivalent of "Visible for", if you have clear descriptive names
> of your Viewing Access Levels (and not something like "Special", who the
> heck is special?!) it makes sense. In that case you set an article "Visible
> for": "Any site visitor"/"Logged in users"/"Webmasters" as an example.
>
> So yes, I would love to see a better label for this. Access seems to
> confuse people with "editing access", this might be a language thing too.
> In my opinion a label that clearly describes it is only about "Viewing"
> would be welcome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/11#issuecomment-68834594>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
I have created a stage 2 task as above.

Waiting on feedback to decide on point 1 above

**Comment by chrisdavenport** [comment]
I suggest we just leave it alone for now.  I don't think "Access" is a good word to use in that context as we have a long history of talking about acess levels when referring to the action-permissions stuff, so we'd be in danger of increasing the confusion.  I actually like Sander's word "visibility" much more (or "visibility groups") as that is much more descriptive of what they are.  However, what we are trying to do here is fix incorrect semantics and that should be Stage 2 and not Stage 1.

**Comment by brianteeman** [comment]
Closing and leaving to Stage 2

Thanks all

**Comment by brianteeman** [comment]
@chrisdavenport @sanderpotjer  do you have any further thoughts on this I just really want to have one term that is used consistently

Currently we have 
Access Levels in the main menu of the Users component
Viewing Access Levels in the sidebar menu and title of the Users component
and
User Groups Having Viewing Access in the Edit Viewing Access Level of the Users component

and lots of other uses throughout the CMS

**Comment by hdouglassmith** [comment]
Brian

As we have already discovered this is a bit of a nightmare but one we really ought to try and sort since it could potentially simplify and enhance users understanding of the product.

For my own thoughts:

Technically speaking I think part of the consideration here is to ignore/get rid of 'Viewing Access' my reasoning here is that 'Access' naturally implies as the very minimum, 'Viewing', therefore to stipulate 'viewing access level' is in my view irrelevant. Therefore if we always refer to 'Access Levels' we lead into a further consideration of the type of access when it could be View(Read) Write(Create/Amend/Delete)

In the absence of anything else, I am happy to bow to Sander's suggestions as his ACL component seems to have opened up this whole area and greatly simplified it.

Best regards
Hugh

**Comment by brianteeman** [comment]
@hdouglassmith So you think "Visibility"

**Comment by hdouglassmith** [comment]
Yes, like that
Hugh

**Comment by Hils** [comment]
A question: if something uses an accepted phrase such as ACL in computing generally, is it wise for Joomla to change this? https://en.wikipedia.org/wiki/Access_control_list ?

**Comment by brianteeman** [comment]
No one is suggesting changing ACL are they?

**Comment by sanderpotjer** [comment]
My main suggestion would still be something around visibility/view/read rather then access. 

So maybe:
Access Levels - > "Visibility Levels"
Viewing Access Levels -> "Visibility Levels"
Access (label when editing article e.g.) -> "Visible for" or "Visibility" 

For EN native speakers: is visibility indeed a proper English word to describe this area of Joomla?

**Comment by brianteeman** [comment]
From an en perspective it's not an ideal word. It makes sense the way you
are using it but it certainly wouldn't be normal usage. Unfortunately I am
struggling to think of a better one.

**Comment by brianteeman** [comment]
I will try to do some research to see what others use. It might be that
just "visibility" on its own is OK

**Comment by brianteeman** [comment]
Does it make sense to use the word "level" if you are creating a role based
acl and not a hierarchy

**Comment by chrisdavenport** [comment]
(Brian beat me to it).

I like Sander's suggestion except for the word "levels".  That brings to mind some sort of hierarchy where one group is at a higher level and has wider permissions than those below.  That may be how many people will set up their websites, and it is inherent in the default (sample) data, but it isn't a requirement.  Perhaps use "groups" instead?

**Comment by brianteeman** [comment]
"Visibility Groups" just sounds wrong though.

On 21 July 2015 at 10:06, Chris Davenport <notifications@github.com> wrote:

> (Brian beat me to it).
>
> I like Sander's suggestion except for the word "levels". That brings to
> mind some sort of hierarchy where one group is at a higher level and has
> wider permissions than those below. That may be how many people will set up
> their websites, and it is inherent in the default (sample) data, but it
> isn't a requirement. Perhaps use "groups" instead?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/11#issuecomment-123224993>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by chrisdavenport** [comment]
It sounds right to me, but maybe I'm too close to the code.  We need a "newbie" perspective, I think.

**Comment by sanderpotjer** [comment]
"Visibility Groups" might sounds wrong, but is correct. The now called "Access Levels" are groups of User Groups. But might be confusing with the User Groups. So synonym of Group, like collection/cluster/category/etc.. ? Not sure if that will get to a better result then "Group" though.

**Comment by brianteeman** [comment]
Perhaps if I do a PR and see what people say? Not sure how else to reach a
larger group right now

On 21 July 2015 at 10:11, Chris Davenport <notifications@github.com> wrote:

> It sounds right to me, but maybe I'm too close to the code. We need a
> "newbie" perspective, I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/11#issuecomment-123227235>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by hdouglassmith** [comment]
For my own assistance, I have listed the uses below to help provide some context:

User Manager -> Viewing Access Levels (This then leads to the heading 'User Groups Having Viewing Access)
There is an inconsistency here in that the drop down menu for Users shows 'Users ->Access Levels' but that is expanded in the left menu to 'Viewing Access Levels'

I think 'Access' on its own is wrong, we should stick with View or Viewing

Personally, I would change to User Manager -> View Access Levels and then change the heading to 'User Groups having View Access'


Best regards
Hugh

**Comment by brianteeman** [comment]
> "Visibility Groups" might sounds wrong, but is correct. 

I will do a PR using this term and then it will be easier for everyone to see it and comment

**Comment by brianteeman** [comment]
Just to confirm - changing to Visibility Groups will also mean the same change elsewhere but sometimes just to the single word Visibility

### Batch processing - Before ###
![before](https://cloud.githubusercontent.com/assets/1296369/8797665/e4373ffe-2f94-11e5-84fd-aa2ff2616b77.png)

### Batch processing - After ###
![after](https://cloud.githubusercontent.com/assets/1296369/8797743/5f25a6b0-2f95-11e5-8672-d07a78acb7ca.png)

### Article Manager - Before ###
![before-a](https://cloud.githubusercontent.com/assets/1296369/8797796/bf73ab2a-2f95-11e5-95c6-7221c6c93ada.png)

### Article Manager - After ###
![after-a](https://cloud.githubusercontent.com/assets/1296369/8797801/c4dd9ddc-2f95-11e5-9f9f-5679a9dafae3.png)

**Comment by sanderpotjer** [comment]
Looks correct to me, thanks Brian.

**Comment by brianteeman** [comment]
OK great - I wont post the PR for a few days as I have a really big one to remove the word manager etc that @rgmears is creating the images for that will be pushed first

**Comment by brianteeman** [comment]
@chrisdavenport Should I do anything about the use of the term Access Level in the code comments

**Comment by chrisdavenport** [comment]
Good question.  I'd say not at this stage.  Let's get the UI change fixed first, then we can look at the code to see about aligning with a "ubiquitous language" (to borrow a DDD expression).

**Comment by brianteeman** [comment]
Thanks

On 21 July 2015 at 12:29, Chris Davenport <notifications@github.com> wrote:

> Good question. I'd say not at this stage. Let's get the UI change fixed
> first, then we can look at the code to see about aligning with a
> "ubiquitous language" (to borrow a DDD expression).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/11#issuecomment-123273141>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
Perhaps it would be better to use standard jargon here. When working with files in File Manager (cPanel, etc) the term is permissions: Read . Write . Execute.

Change Write to Publish 
and 
Execute to Edit

![user_interface_permissions](https://cloud.githubusercontent.com/assets/4270063/8800251/c99969d8-2f76-11e5-9b6b-53f1435b2900.png)

**Comment by brianteeman** [comment]
unfortunately our software doesnt work like that

On 21 July 2015 at 13:05, Robert G Mears <notifications@github.com> wrote:

> Perhaps it would be better to use standard jargon here. When working with
> files in File Manager (cPanel, etc) the term is permissions: Read . Write .
> Execute.
>
> Change Write to Publish
> and
> Execute to Edit
>
> [image: user_interface_permissions]
> <https://cloud.githubusercontent.com/assets/4270063/8800251/c99969d8-2f76-11e5-9b6b-53f1435b2900.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/11#issuecomment-123285154>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
I know Joomla is different. But what you are doing with Access levels is exactly the same. Elsewhere in computerdom it's called Permissions. And in Joomla there are two kinds: Front End and Backend.

**Comment by rgmears** [comment]
Both WordPress and Drupal use the word "Roles".

WordPress does this: https://codex.wordpress.org/Roles_and_Capabilities

Drupal does this: https://www.drupal.org/node/120614

**Comment by sanderpotjer** [comment]
The now called Access Levels are not Roles in Joomla. If you would use the word Roles it would be for what we now call "User Groups" for which you can configure the permissions.

**Comment by brianteeman** [comment]
> And in Joomla there are two kinds: Front End and Backend.

Actually there are not. Thats the problem with the current terminology that
you think that is the case.

In Joomla there are currently Access Levels which determine what you can do
and Viewing levels which determine what you can see

On 21 July 2015 at 13:34, Robert G Mears <notifications@github.com> wrote:

> Both WordPress and Drupal use the word "Roles".
>
> WordPress does this: https://codex.wordpress.org/Roles_and_Capabilities
>
> Drupal does this: https://www.drupal.org/node/120614
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/11#issuecomment-123291266>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
Right. Access Levels are backend (although some of it can be done from the front end); more properly called administrative (Administration). And Viewing Levels are only visible in the front end or public face of a website.

**Comment by rgmears** [comment]
Splitting hairs being what it is: 
Access Levels are what a person can do. 
Viewing Levels are what a person can see.

**Comment by brianteeman** [comment]
Yes but Level implies a hierarchical structure and as discussed above they
do not have to be. In fact with a role based acl structure as can be see
here (
http://magazine.joomla.org/issues/issue-sept-2012/item/856-implementing-role-based-acl)
they are not levels at all.



On 21 July 2015 at 14:11, Robert G Mears <notifications@github.com> wrote:

> Splitting hairs being what it is:
> Access Levels are what a person can do.
> Viewing Levels are what a person can see.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/11#issuecomment-123299869>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
So the word Levels seems to be the problem:

Access Levels to Access (what a person can do).
Viewing Levels to View (what a person can see).

And it's all under Permissions:
Permissions
 -> Access
 -> View

**Comment by rgmears** [comment]
Or it's all under Access:
Access
 -> Edit
 -> View

**Comment by brianteeman** [comment]
@chrisdavenport and I spent quite a bit of time looking at this during joomladay germany. One of the major problems is that Access Levels are not really levels at all but groups.

What we came up with was to change Viewing Access Levels => Visibility Groups in the component and to change Access to Visibility when it is referred to in other components eg com_content

Thoughts?

**Comment by sanderpotjer** [comment]
Quite in line with what I suggested before, so +1 :-)

**Comment by hdouglassmith** [comment]
That sounds like a much more logical solution, I would support it
Best regards
Hugh

**Comment by brianteeman** [comment]
Thanks guys - I will try to get the PR created this week. Its surprisingly
a very big PR as when we dug into it we discovered that the message strings
etc are even worse than the visible strings so it will need a careful
manual review of each one.

When the PR is completed I will post back here and would really appreciate
it if you could test it. I really dont want to go through the "abuse" I
received over the removal of manager again alone

On 21 September 2015 at 12:43, hdouglassmith <notifications@github.com>
wrote:

> That sounds like a much more logical solution, I would support it
> Best regards
> Hugh
>
> From: Brian Teeman <notifications@github.com<mailto:
> notifications@github.com>>
> Reply-To: joomla/user-interface-text <reply@reply.github.com<mailto:
> reply@reply.github.com>>
> Date: Monday, 21 September 2015 06:33
> To: joomla/user-interface-text <user-interface-text@noreply.github.com
> <mailto:user-interface-text@noreply.github.com>>
> Cc: Hugh Douglas-Smith <hugh@webappz.co.uk<mailto:hugh@webappz.co.uk>>
> Subject: Re: [user-interface-text] Viewlevel Access - Consistency Check
> (#11)
>
>
> @chrisdavenport<https://github.com/chrisdavenport> and I spent quite a
> bit of time looking at this during joomladay germany. One of the major
> problems is that Access Levels are not really levels at all but groups.
>
> What we came up with was to change Viewing Access Levels => Visibility
> Groups in the component and to change Access to Visibility when it is
> referred to in other components eg com_content
>
> Thoughts?
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/joomla/user-interface-text/issues/11#issuecomment-141936301
> >.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/11#issuecomment-141938706>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Having thought this over I am not prepared to submit this PR. Life just isnt worth the hassle

**Comment by brianteeman** [comment]
We decided not to proceed any further with the idea to change the terminology for ACL and Viewing Levels as it is too big a change after all these years.
