### ISSUE TITLE
User group consistency

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#13]
We use a mixture of   
* Usergroup
* user group

and numerous capitalisations and combinations

**Comment by brianteeman** [comment]
[Group or User Group - inconsistency  ](http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=21734)

**Comment by Hutchy68** [comment]
Are there any rules to reference? Seems to me user group as two words is appropriate. A specific proper named group, Joomla! User Group, would be correct. Usergroup as one word, not correct.

**Comment by brianteeman** [comment]
I've not found anything yet - still looking

On 5 January 2015 at 21:12, Tom Hutchison <notifications@github.com> wrote:

> Are there any rules to reference? Seems to me user group as two words is
> appropriate. A specific proper named group, Joomla! User Group, would be
> correct. Usergroup as one word, not correct.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/13#issuecomment-68782329>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
I can't find anything documented but a google search for the term on both gov.uk and bbc.co.uk seems to indicate the the government and the bbc use two words not one

**Comment by chrisdavenport** [comment]
"usergroup" doesn't look like a proper word to me, so I think I prefer two words.

**Comment by Hutchy68** [comment]
Two words -- Even phone tries to autocorrect making two words.

**Comment by hdouglassmith** [comment]
Oxford dictionary defines it as 2 words

**Comment by brianteeman** [comment]
Whoops - I already changed this in the PR and added it to the styleguide as two words - glad you all agree ;)
