### ISSUE TITLE
eg

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#15]
The main source for the style guide [GOV.UK Style Guide] (https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style) says
> eg, etc and ie
Don’t use full stops after or between these notations.

> If you want to use the long form (‘for example’ instead of ‘eg’, ‘specifically’ instead of ‘ie’ etc) then this is at the content designer’s discretion. User testing has shown that some people are not familiar with abbreviations such as eg, so consider your audience before abbreviating.

I tried it and while it works ok for ie and etc it just looks wrong to me for eg so I haven't applied it yet

**Comment by Hils** [comment]
>eg, etc and ie
>Don’t use full stops after or between these notations.

I have used all three without full stops for several years now. If the rule applies to two, it should apply to all in my view.

**Comment by brianteeman** [comment]
Yeah thats what I think as well which is why I wrote all three in the guide
but when I went to apply it - well it just looked odd

On 5 January 2015 at 02:00, Hils <notifications@github.com> wrote:

> eg, etc and ie
> Don’t use full stops after or between these notations.
>
> I have used all three without full stops for several years now. If the
> rule applies to two, it should apply to all in my view.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/15#issuecomment-68660422>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Just checked my secondary source of the BBC style guide and they also use eg - so I will bite the bullet and commit it
