### ISSUE TITLE
Super User or Super Administrator in the Install

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#17]
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=31883

We have removed all other references to super administrator - just this one left was I wrong in the comment I made in the link above

**Comment by Hils** [comment]
Unfortunately I can't load joomlacode atm. But I like Super Administrator in the install. There can be many Super Users now but only one SA - the person who installs the site. But after install, would they just transform into a SU?

**Comment by brianteeman** [comment]
That's the thing Hils. There really is no such thing at all as a Super
Administrator any more afaict

On 5 January 2015 at 18:32, Hils <notifications@github.com> wrote:

> Unfortunately I can't load joomlacode atm. But I like Super Administrator
> in the install. There can be many Super Users now but only one SA - the
> person who installs the site. But after install, would they just transform
> into a SU?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/17#issuecomment-68752655>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hils** [comment]
just put it down to me reminiscing then :D

**Comment by chrisdavenport** [comment]
I'd go with "Super User" throughout.

**Comment by hdouglassmith** [comment]
I generally have a problem with 'administrator' in that plenty of users have difficulty spelling it. Super User would get my vote

**Comment by brianteeman** [comment]
Thanks I will add this to the style guide and make the PR
