### ISSUE TITLE
Rename Custom HTML module

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#18]
[Previous discussion](http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=31916)

Based on comments from beginners they found the name "Custom HTML" confusing. It is not just html. It could be images, javascript basically anything at all. That is why it should be just named Custom

After requesting feedback on this over twitter it would appear that even experienced users were not happy that this module name correctly described the module.
There were many different suggestions proposed but I have chosen to keep it simple and just rename the 2 modules (site and admin modules) to Custom.
This removes the confusing word HTML and importantly will ensure that it doesnt change its position in the alphabetical list of modules in en-GB and hopefully most other languages.

As you can see from the previous discussion the dropping of HTML was argued against mainly by a french speaker who even stated that in french they dont use the HTML in their translation. In fact it is not a translation but a completely different string used in french.

>Contenu personnalisé
>Le module 'mod_custom' permet de créer vos propres modules personnalisés en y intégrant les contenus souhaités à l'aide de l'éditeur et, de code si les droits de l'éditeur et de Joomla vous le permettent.

**Comment by vdrover** [comment]
I like this change. Nice idea.

**Comment by Hils** [comment]
Agree. One thing for later "This Module allows you to create your own HTML Module using a WYSIWYG editor." It allows much more than just HTML doesn't it?

**Comment by Hutchy68** [comment]
I am fine with Custom or even Custom Content. @Hils is correct, it doesn't have to be HTML it could even be JavaScript.

**Comment by Hutchy68** [comment]
On second thought, maybe not Custom Content. Custom Code, but Custom as one word is ok too.

**Comment by brianteeman** [comment]
Yes I would change the description text as well

On 5 January 2015 at 18:23, Tom Hutchison <notifications@github.com> wrote:

> On second thought, maybe not Custom Content. Custom Code, but Custom as
> one word is ok too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/18#issuecomment-68751288>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by hdouglassmith** [comment]
My preference would be 'Custom Content' rather than just custom, but either is better without the HTML

**Comment by brianteeman** [comment]
@hdouglassmith my argument against "custom content" is that you might be using it for just some javascript - is that content? and is an image content? Many people think content =words

**Comment by Hutchy68** [comment]
Custom with the description change to explain use, HTML, JS, etc sounds good to me.

**Comment by brianteeman** [comment]
Is that something you think I can push through now or should it wait for stage 2 as it could be seen to effect TT

**Comment by Hutchy68** [comment]
If description is updated that would be a stage 2.

**Comment by rgmears** [comment]
While many people think content=words, anything that displays in a web page is content.

**Comment by Hils** [comment]
>While many people think content=words, anything that displays in a web page is content.

That is right and perhaps exactly the reason why just the word custom should be used on its own because many people will understand it for their purpose. Any further clarification could be in the description.

**Comment by brianteeman** [comment]
Thanks - this will be done in stage 2

On 6 January 2015 at 09:36, Hils <notifications@github.com> wrote:

> While many people think content=words, anything that displays in a web
> page is content.
>
> That is right and perhaps exactly the reason why just the word custom
> should be used on its own because many people will understand it for their
> purpose. Any further clarification could be in the description.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/18#issuecomment-68844302>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
I suggest that what you call stage 2, i.e. changing the meaning of a string value, be merged before language freeze (i.e. beta), while any en-GB stuff only (capitalisation, end of phrase period, etc.) would be merged after the freeze.
This will let us make clean diff(s) for the Translation teams.

**Comment by brianteeman** [comment]
So is it better for you to have the two stages reversed?

To be honest it is easier to do it the other way AND leave stage 2 until
after the release of 3.4. That was the intention and allows more time for
TT to apply/check those  changes.

**Comment by brianteeman** [comment]
Just noticed that in 2.5 the text directly above the textarea for entry was called Custom Output. That string disappeared in J3 (except for in Hathor)

**Comment by brianteeman** [comment]
PR submitted http://issues.joomla.org/tracker/joomla-cms/6555
