### ISSUE TITLE
Show/Hide Show/Display

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#20]
We have a mixture of 
`Show/Hide Show or Hide or Display`

**Comment by brianteeman** [comment]
Show/Hide 44 occurrences
`COM_CONTACT_FIELD_BREADCRUMBS_DESC="Show/Hide category breadcrumbs."`

Show or hide 45 occurrences
`COM_CONTACT_FIELD_EMAIL_SHOW_FORM_DESC="Show or Hide contact form."`

Display or hide 4 occurrences
`COM_CONTENT_SHOW_IMAGES_URLS_BACK_DESC="Display or hide fields to insert images and links in the Administrator."`

Show on its own 195 occurrences
`COM_CONFIG_FIELD_METAVERSION_LABEL="Show Joomla! Version"`

Hide on its own 8 occurrences
`COM_INSTALLER_LABEL_HIDEPROTECTED_LABEL="Hide Protected Extensions"`

Display on its own 95 occurrences
`COM_CONFIG_CONFIG_VIEW_DEFAULT_TITLE="Display Site Configuration Options"`

**Comment by Hutchy68** [comment]
Hmm, I would say "Show or Hide" in usage. Show means "make seen" or to make it possible for something to be seen.

**Comment by chrisdavenport** [comment]
"Show or Hide".

**Comment by hdouglassmith** [comment]
I think Show/Hide the slash is generally used to differentiate between radio type options

**Comment by brianteeman** [comment]
Not easy this stuff is it?

**Comment by rgmears** [comment]
Is there a difference in what occurs? Or are all of these descriptors just different ways of saying the same thing?

**Comment by b2z** [comment]
I think that there are two different contexts if we are talking about "Show" and "Display". 

"Display" should be used for general situations like `COM_CONFIG_CONFIG_VIEW_DEFAULT_TITLE="Display Site Configuration Options"`. Here something is displayed and can not be hidden.

"Show" should be used with "Hide". You can "Show" something or "Hide" something. I would vote for "Show or Hide" here.

**Comment by brianteeman** [comment]
Dmitry - that is exactly what I am thinking as well.

It will mean a manual review of all the strings to see the context that
they are in but I will put it on the todo list

On 6 January 2015 at 09:57, Dmitry Rekun <notifications@github.com> wrote:

> I think that there are two different contexts if we are talking about
> "Show" and "Display".
>
> "Display" should be used for general situations like COM_CONFIG_CONFIG_VIEW_DEFAULT_TITLE="Display
> Site Configuration Options". Here something is displayed and can not be
> hidden.
>
> "Show" should be used with "Hide". You can "Show" something or "Hide"
> something. I would vote for "Show or Hide" here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/20#issuecomment-68846436>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Moving to a stage 2 task

**Comment by brianteeman** [comment]
I have done a PR to standardise on `Show or hide`
