### ISSUE TITLE
email address

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#22]
email should refer to the item that you send  
email address should be used if referring to their actual address  

So strings like this one
`COM_ADMIN_USER_FIELD_EMAIL_DESC="Enter an email for the user."`
should be changed to
`COM_ADMIN_USER_FIELD_EMAIL_DESC="Enter an email address for the user."`

And strings like this one
`COM_CONFIG_FIELD_MAIL_MAILER_DESC="Select which mailer for the delivery of site email."`
are not changed

**Comment by Hils** [comment]
Agree!

**Comment by Hutchy68** [comment]
Agree

**Comment by chrisdavenport** [comment]
+1

**Comment by hdouglassmith** [comment]
Agree

**Comment by brianteeman** [comment]
OK thanks I will add this to the docs and make the pull request
