### ISSUE TITLE
Extensible or extendable

### ISSUE THREAD

**Issue by chrisdavenport** [joomla/user-interface-text#25]
Should we change "extensible" to "extendable"?  Those darn Americans keep inventing new words when there is a perfectly good word already in the dictionary!

**Comment by brianteeman** [comment]
I checked this one carefully and they actually have possibly slightly different meanings

The think that pushed me towards accepting "extensible" was  that XML is 'extensible markup language'
and
> 'Extensible' seems therefore to mean something that can be added to like XML, whereas 'extendable' would apply to something more like a telescopic lens,

So in this single example I went with extensible unless you disagree?

**Comment by hdouglassmith** [comment]
not sure I agree with you Brian, dictionary defintion of 'extensible' is 'something capable of being extended' there are lots of words which follow a similar pattern and are typically interchangable.

    comprehendible, comprehensible
    corrodable, corrodible, corrosible
    defendable, defensible
    deridable, derisible
    dividable, divisible
    evadable, evasible
    expandable, expansible
    explodable, explosible
    extendible, extensible
    inevadible, inevasible
    invadable, invasible
    offendable, offensible
    persuadable, persuasible
    protrudable, protrusible
    reprehendable, reprehensible
    rescindable, rescindible
    revisable, revisible
    subdividable, subdivisible
    suspendible, suspensible
    undefendable, undefensible
    undividable, undivisible

**Comment by brianteeman** [comment]
OK - it is only used once and its such an obscure word I doubt anyone would even notice it

Any objections to me removing it from the style guide and changing the one instance of it to extendable
