### ISSUE TITLE
admin or administrator

### ISSUE THREAD

**Issue by chrisdavenport** [joomla/user-interface-text#26]
There are many occurrences of "admin" as an abbreviation for "administrator".  Should we be consistent and expand them all?

**Comment by brianteeman** [comment]
we should but there currently is an issue that admin is used to represent both a user and the backend.

Definitely an issue to address but one I would prefer to leave open for now and address later

**Comment by Hils** [comment]
frontend admin also

**Comment by Hils** [comment]
Just noticed this in #20 
>COM_CONTENT_SHOW_IMAGES_URLS_BACK_DESC="Display or hide fields to insert images and links in the Administrator.

An obvious case of misuse of Administrator - it should be admin or administration.

**Comment by brianteeman** [comment]
This is one of the biggest issues Hils

because the url is /administrator and not /administration

which is why in many places we tried in the past to write backend

On 6 January 2015 at 09:41, Hils <notifications@github.com> wrote:

> Just noticed this in #20
> <https://github.com/joomla/user-interface-text/issues/20>
>
> COM_CONTENT_SHOW_IMAGES_URLS_BACK_DESC="Display or hide fields to insert
> images and links in the Administrator.
>
> An obvious case of misuse of Administrator - it should be admin or
> administration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/26#issuecomment-68844875>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hils** [comment]
It's at this point I don't understand why the url is dictating the content rather than the other way round :( Is that a routing thing?

**Comment by brianteeman** [comment]
I am going to create a Stage 2 task for this

Replace all occurrences of admin and administrator with with Backend

Might as well do it all at once

**Comment by Hils** [comment]
why would that be capitalised Brian please? Is there a link, yet, to that rule? Backend

**Comment by brianteeman** [comment]
Stage 2 PR are all to be reviewed seperately

This was in the very original Word2Watch list from 6 years ago

On 6 January 2015 at 14:40, Hils <notifications@github.com> wrote:

> why would that be capitalised Brian please? Is there a link, yet, to that
> rule? Backend
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/26#issuecomment-68872852>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
See https://github.com/joomla/joomla-cms/pull/7433
