### ISSUE TITLE
nonbreaking or non-breaking

### ISSUE THREAD

**Issue by chrisdavenport** [joomla/user-interface-text#27]
My feeling is that it should be hyphenated.

**Comment by hdouglassmith** [comment]
As a general observation are we looking to increase or decrease the use of hyphens? to my mind a rule to eliminate them might help simplify things?

**Comment by brianteeman** [comment]
General view on hyphenation
https://github.com/joomla/user-interface-text/blob/master/punctuation.md#hyphenation

Does anyone know what the official specification for html characters says for nonbreakingspace

We should go with that as it is only used in joomla in the tinymce wyswiyg editor for `&nbsp;`

**Comment by brianteeman** [comment]
Found it http://www.w3.org/TR/html4/sgml/entities.html#h-24.2.1
It should indeed be hyphenated.

**Comment by infograf768** [comment]
If this chnage is needed in TinyMCE, a ticket should be posted at their site as English texts are included in their js.

**Comment by brianteeman** [comment]
I will speak to joakim

On 6 January 2015 at 07:22, infograf768 <notifications@github.com> wrote:

> If this chnage is needed in TinyMCE, a ticket should be posted at their
> site as English texts are included in their js.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/27#issuecomment-68834278>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
