### ISSUE TITLE
_QQ_

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#28]
Do we still need this? I dont think we do and have removed all the regular uses of it. Now have to try and remove the href that use it and the comments

**Comment by brianteeman** [comment]
I have removed it from the strings where it was being used as a speack mark in text and replaced with `&quot;` with no problem. But if I try to do the same on a url it doesnt work you end up with
`http://localhost/joomla-cms/administrator/%22http://skin.tinymce.com%22`

If I put regular `"` instead of the _QQ_ here then it works ok - as far as i can tell

Thoughts?

**Comment by brianteeman** [comment]
@mbabker @wilsonge is this safe

**Comment by mbabker** [comment]
IIRC it was needed because of PHP 5.2 issues, it isn't an issue to use standard quotes in PHP 5.3+.  I believe @nikosdion mentioned at some point he removed it from his language strings without issue.

**Comment by brianteeman** [comment]
Yes removing it from strings has been fine -  I dont understand why you
cant use `&quot;` inside a href but hey I will just use regular `"`

On 6 January 2015 at 00:59, Michael Babker <notifications@github.com> wrote:

> IIRC it was needed because of PHP 5.2 issues, it isn't an issue to use
> standard quotes in PHP 5.3+. I believe @nikosdion
> <https://github.com/nikosdion> mentioned at some point he removed it from
> his language strings without issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/28#issuecomment-68810401>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
&quot; is an HTML character entity which tells the browser to display typographer's quotes. As do &#8220; or &#8221; . It's not appropriate for href.

**Comment by rgmears** [comment]
&amp;quot; is an HTML character entity which tells the browser to display typographer's quotes. As do &amp;#8220; or &amp;#8221; . It's not appropriate for href.

**Comment by infograf768** [comment]
Until we solve the debug, please do NOT change `"_QQ_"` to `"` for URLs and classes in the string values, as doing this will mark the file as parsing Error when debug language is on.

**Comment by brianteeman** [comment]
Ok I will leave this and move it to a stage 2 task where it can be handled
with debug
