### ISSUE TITLE
Finalising the DISPLAY of the style guide

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#29]
Using the docs that I have created already I have found it overly complex because I have separated issues into individual files.

I think it is going to be much easier to use if it is one single document sorted alphabetically. Preferably with anchors for each letter etc something like this (https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style)

Thoughts?

**Comment by wilsonge** [comment]
Personally I like what we have. But probably what's needed is a navigation page. At the end what we probably need is a github.io page like the code style have. Rather than a collection of markdown documents.

**Comment by brianteeman** [comment]
My 2c
github.io is just a nice interface to markdown documents. It doesnt have
search? and because its not a single page you cant ctrl-f to search either


On 7 January 2015 at 14:23, George Wilson <notifications@github.com> wrote:

> Personally I like what we have. But probably what's needed is a navigation
> page. At the end what we probably need is a github.io page like the code
> style have. Rather than a collection of markdown documents.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/29#issuecomment-69027694>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
At a quick google Microsoft have something here that's searching https://microsoft.github.io/ although I suspect it is pretty limited in functionality.

Having said that the page you referenced doesn't really have search either as you need to know what letter your thing is sectioned under before you can do ctrl-f.

I'll have a think about it

**Comment by brianteeman** [comment]
at least you can ctrl-f thats my point. Its a minimum requirement

On 7 January 2015 at 14:40, George Wilson <notifications@github.com> wrote:

> At a quick google Microsoft have something here that's searching
> https://microsoft.github.io/ although I suspect it is pretty limited in
> functionality.
>
> Having said that the page you referenced doesn't really have search either
> as you need to know what letter your thing is sectioned under before you
> can do ctrl-f.
>
> I'll have a think about it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/29#issuecomment-69030050>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
A single document would work if it can be downloaded and opened in a text editor like notepad++.

**Comment by brianteeman** [comment]
Looks like you can cheat to create search https://github.com/cobbler/jekyll-dynamic-search

**Comment by brianteeman** [comment]
Any good docs for how to make a github io page?
Maybe I can just fork the coding style one

**Comment by wilsonge** [comment]
@Hutchy68 has been dealing with this a lot recently. Any good thoughts?

**Comment by brianteeman** [comment]
I really think we should be eating our own dog food and use Joomla

On 28 January 2015 at 19:44, George Wilson <notifications@github.com> wrote:

> @Hutchy68 <https://github.com/Hutchy68> has been dealing with this a lot
> recently. Any good thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/29#issuecomment-71901666>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
I don't disagree. But I just don't have enough hands to write the code to build a component that allows public editing, public to view previous revisions but not actually be able to revert in a com_content style setting. Until I do or someone else does we just have to stick with the tools that are available to us I think. Which is either github markdown or the wiki

**Comment by brianteeman** [comment]
I am not convinced that for this guide we need a custom component. The
reason for not using joomla would be for collaborative and audited edits.

Do you really think that once published this will need to be edited very
often - I dont.

In my head we would ideally have one web site that covers the guides for
coding, en-gb and localisation and I see no reason why they cant be a
section on developer.joomla.org - I know that is where I would be looking
for the information.

As for handling the "collaborative and audited edits" this cold be handled
by having that take place on github and on the occasions that updates are
made they are manually copied across to the joomla web site. Not ideal but
I think it will only happen rarely.

On 28 January 2015 at 22:29, George Wilson <notifications@github.com> wrote:

> I don't disagree. But I just don't have enough hands to write the code to
> build a component that allows public editing, public to view previous
> revisions but not actually be able to revert in a com_content style
> setting. Until I do or someone else does we just have to stick with the
> tools that are available to us I think. Which is either github markdown or
> the wiki
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/29#issuecomment-71930456>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
What do people think of this

Dear PLT. 
The en-GB style guide needs a permanent home that is more visible than a github repo.

The guide itself should be easily available for core and extension developers to **find** and **use** (and hopefully for localisers and translators). To make it easy to find it should be on a joomla.org site. To make it really usable it needs to be searchable. 

As it is not very large can it be a category on developer.joomla.org? Possibly with its own search plugin so you can search just the style guide.

This github repo would be kept for issue management and for any comments or edits to the style guide itself. When any change is made to the style guide is accepted it is copied to the j.org web site. Today that has to be a manual process but who knows maybe in the future someone will write a component to connect github and joomla content.

The work the code style team has done on github.io is great but we really feel we should be eating our own dog food and using joomla for the joomla en-GB style guide.

**Comment by rgmears** [comment]
Agree.

**Comment by Hils** [comment]
First - who wrote that email? Has it been sent to the PLT by a third party? There is no signature.

Second - 

Thinking a bit more radically here. I think we as a workgroup should work in GitHub.  Our work could then be automatically sent to  eg Transifex via their Client. Then it could be translated easily (.po files). Then it could be automatically put on developer.joomla.org in many languages. One smooth workflow which will always be up to date. An example of a similar project (add files to transifex from GitHub, translate, then retrieve & make available for download on a site - crowd translating & continuous ) in progress is CTransifex - a component written by Compojoom to interface with Transifex and to retrieve translations. https://compojoom.com/joomla-extensions/ctransifex-language-distribution-made-easy

Just one example of part of the process we would need. 

The process I suggest is working now and it is our own dogfood made by Joomlers and integrated with our CMS. 

I really feel that we should be using up to date methods of working with this kind of project which basically means as much automation as possible via the best tools available!

**Comment by brianteeman** [comment]
1. I wrote it and as it says it's an idea
2. Po files and using transifex are not up for discussion here and will not
be discussed here. It is not for this group to change the way translations
are manages in joomla. If that an what you thought then you are mistaken

**Comment by Hils** [comment]
Brian - may I say again - we are working as a Team. Teams discuss
things together. "will not be discussed here" is not acceptable in a team situation. What I said was that I think we should continue to use GitHub. We need to learn how to automate properly and that has to include translations. Having been particularly careful not to mention OpenTranslators (please note that) but merely to give an example of workflow. It is nothing to do with core translations and I am not sure why you made that comment. I think you were mistaken. I disagree that we should leave GitHub and eat some kind of yet to be invented dog food as opposed to dog food that has been matured and is tasty. We will get on much better if we brainstorm as opposed to being controlled.

**Comment by brianteeman** [comment]
Sorry hils. This working group has a defined role. Anyone is welcome to
discuss things within that role. Otherwise it is not for this group. If you
can't accept that then sadly this group is not for you. Too many working
groups get sidetracked I am not going to allow that to happen here. We have
enough to do.

**Comment by brianteeman** [comment]
A reminder of the role of this working group

http://developer.joomla.org/news/600-announcement-en-gb-user-interface-text-working-group.html

**Comment by mbabker** [comment]
The CMS already has the tools to work with GitHub via the JGithub classes (or the Framework equivalents).  So to sync data between a CMS install and a GitHub repository is a matter of writing a cron job to update on a fixed schedule, fetch the contents from the repository files (standardized to ensure a script can work correctly), and inject those contents into an article.

Dependent on structure of the guide, either the contents should be combined to a single file (matching a single item in a Joomla install) or require a one item per file mapping.  Contents should either be in HTML or Markdown format, with the latter requiring our script to render it into HTML via GitHub's API connection.  The simplest of options would be to just add a category to com_content and publish the guide's contents within it.  Noting your search comment, either a specialized search plugin would need to be written to limit com_content searches to within the guide's category(-ies) (the developer site is using Smart Search FWIW) or the content would need to go into a new component and a plugin written supporting that.

Lastly, entertaining the translations option for a moment.  If translated content is in the same repository as the one the above script is already synchronizing to, then it's a matter of updating the script to account for that possibility.

**Comment by brianteeman** [comment]
Thanks @mbabker thats exactly the technical news I hoped to hear. Even
better news that Smart Search is being used on that site as that makes
custom searches much easier.

On 30 January 2015 at 21:42, Michael Babker <notifications@github.com>
wrote:

> The CMS already has the tools to work with GitHub via the JGithub classes
> (or the Framework equivalents). So to sync data between a CMS install and a
> GitHub repository is a matter of writing a cron job to update on a fixed
> schedule, fetch the contents from the repository files (standardized to
> ensure a script can work correctly), and inject those contents into an
> article.
>
> Dependent on structure of the guide, either the contents should be
> combined to a single file (matching a single item in a Joomla install) or
> require a one item per file mapping. Contents should either be in HTML or
> Markdown format, with the latter requiring our script to render it into
> HTML via GitHub's API connection. The simplest of options would be to just
> add a category to com_content and publish the guide's contents within it.
> Noting your search comment, either a specialized search plugin would need
> to be written to limit com_content searches to within the guide's
> category(-ies) (the developer site is using Smart Search FWIW) or the
> content would need to go into a new component and a plugin written
> supporting that.
>
> Lastly, entertaining the translations option for a moment. If translated
> content is in the same repository as the one the above script is already
> synchronizing to, then it's a matter of updating the script to account for
> that possibility.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/29#issuecomment-72275181>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
NEW Draft after Michaels technical comment

What do people think of this

Dear PLT. 
The en-GB style guide needs a permanent home that is more visible than a github repo.

The guide itself should be easily available for core and extension developers to find and use (and hopefully for localisers and translators). To make it easy to find it should be on a joomla.org site. To make it really usable it needs to be searchable.

As it is not very large can it be a category on developer.joomla.org? Possibly with its own search plugin (or custom smart search) so you can search just the style guide.

This github repo would be kept for issue management and for any comments or edits to the style guide itself. When any change is made to the style guide is accepted it is copied to the j.org web site. Today that has to be a manual process but  Michael has said that joomla core already has the tools to work with GitHub via the JGithub classes and once setup just needs a cron to keep it in sync.

The work the code style team has done on github.io is great but we really feel we should be eating our own dog food and using joomla for the joomla en-GB style guide.

**Comment by rgmears** [comment]
I don't get the colloquialism "eating our own dog food". In the context here it doesn't make sense, to me at least. Other than that you seem to be moving towards a simple, easy to use implementation; which is good. 

Except that her implementation is different, I'm not sure why you dissed @Hils, either, for her suggestion.

**Comment by brianteeman** [comment]
Sorry Robert "eating our own dog food" means using the tools that we create
ourselves  and not other tools - so in this case it means using Joomla to
display content and not some other tool.

We must stick to our focus which is the en-GB text. It is not our role to
discuss how translations of the core of joomla are done nor is it our role
to decide how or if a translation team choses to localise the style guide
for their own use. To be absolutely clear the style guide is not something
that can be translated line by line no matter what the tool used it has to
be localised not translated and they are different things

On 30 January 2015 at 22:17, Robert G Mears <notifications@github.com>
wrote:

> I don't get the colloquialism "eating our own dog food". In the context
> here it doesn't make sense, to me at least. Other than that you seem to be
> moving towards a simple, easy to use implementation; which is good.
>
> Except that her implementation is different, I'm not sure why you dissed
> @Hils <https://github.com/Hils>, either, for her suggestion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/29#issuecomment-72280090>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
@brianteeman
Then it would be better &mdash; formality being a consideration and all &mdash; to say "use our own (Joomla) tools" or Joomla's inbuilt tools &hellip;

**Comment by brianteeman** [comment]
Happy to change it for clarity but it is a fairly common term in the joomla
dev world and all the PLT would understand it.

3rd Draft

Dear PLT.
The en-GB style guide needs a permanent home that is more visible than a
github repo.

The guide itself should be easily available for core and extension
developers to find and use (and hopefully for localisers and translators).
To make it easy to find it should be on a joomla.org site. To make it
really usable it needs to be searchable.

As it is not very large can it be a category on developer.joomla.org?
Possibly with its own search plugin (or custom smart search) so you can
search just the style guide.

This github repo would be kept for issue management and for any comments or
edits to the style guide itself. When any change is made to the style guide
is accepted it is copied to the j.org web site. Today that has to be a
manual process but Michael has said that joomla core already has the tools
to work with GitHub via the JGithub classes and once setup just needs a
cron to keep it in sync.

The work the code style team has done on github.io is great but we really
feel we should be using our own tool (joomla) for the joomla en-GB style
guide especially as the code to connect with github exists in the core.

On 30 January 2015 at 23:13, Robert G Mears <notifications@github.com>
wrote:

> @brianteeman <https://github.com/brianteeman>
> Then it would be better — formality being a consideration and all — to say
> "use our own (Joomla) tools" or Joomla's inbuilt tools …
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/29#issuecomment-72287289>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
> When any change is made to the style guide is accepted it is copied to the j.org web site. Today that has to be a manual process but Michael has said that joomla core already has the tools to work with GitHub via the JGithub classes and once setup just needs a cron to keep it in sync. 

> The work the code style team has done on github.io is great but we really feel we should be using our own tool (joomla) for the joomla en-GB style guide especially as the code to connect with github exists in the core.

When any change is made to the style guide ** and** is accepted**,** it is **then** copied to the j.org **website**. Today that has to be a manual process**;** but Michael has said that **J**oomla core already has the tools to work with GitHub via the JGit**H**ub classes and**,** once **set up,** just needs a cron **job** to keep it in sync. 

The work the code style team has done on github.io is great. **But we** feel we should be using our own **(Joomla)** tool for the **J**oomla en-GB style guide**;** especially as the code to connect with **G**it**H**ub exists in the core.

**Comment by brianteeman** [comment]
Thanks

**Comment by mbabker** [comment]
FWIW the actual class name is JGithub (thank Joomla's auto loader on that)

**Comment by Hutchy68** [comment]
Brian summarized everything pretty well in regards to what the scope of this working group is by linking back to the original announcement. 

As far as localisation, I think it's spelled out pretty well translation teams can fork this repo and use it as a framework to build their own. We can't be drawn into discussions specific to a particular language. There are way too many nuances specific to a language and it's way out of scope for this working group. It is up to the individual translation teams to decide how to interpret the en-GB guide. Of course there will be some crossover such as Joomla! Vs Joomla. 

Where to place the guide, I will leave that up to the team leader, Brian. Whatever decision he makes I will fully support it and try to make it happen.

**Comment by Hils** [comment]
@Hutchy68 
Yes Tom. Brian has done an amazing job to get this project this far so fast. I probably missed some conversations early on due to illness (ongoing). The project was specified but not in great detail as regards to language en-GB. But Brian knows precisely what he wants to do, and he is doing it, so it is better to go with the current flow as there doesn't seem much room for teamwork..

@all
I am confused with all this irrelevant talk of Joomla core translations btw - nothing to do with me or what I do elsewhere. All I was suggesting is that we modernise the whole workflow rather than use an old fashioned way of working or choose yet another method as every other joomla project seems to do.

My contribution really was going to be in the actual en-GB language including grammar. In another life I do a lot of technical en-GB proof reading which has been, for the past 15 years,  a great way to learn preciseness and remove ambiguity. If we are taking media style guides as our base, this isn't perhaps the kind of work you need to be done. I thought that this style guide was to clean up the en-GB in core rather than a general SG which would include content narrative and colloquial en-GB.

So I will step down from this team. I do have strong views on my language and its use but working in this kind of team isn't going to be productive for me or this team. 

Good luck and well done for tackling this much needed area of Joomla. Thank you!

**Comment by brianteeman** [comment]
Sorry to see you go but thats life

On 31 January 2015 at 12:38, Hils <notifications@github.com> wrote:

> @Hutchy68 <https://github.com/Hutchy68>
> Yes Tom. Brian has done an amazing job to get this project this far so
> fast. I probably missed some conversations early on due to illness
> (ongoing). The project was specified but not in great detail as regards to
> language en-GB. But Brian knows precisely what he wants to do, and he is
> doing it, so it is better to go with the current flow as there doesn't seem
> much room for teamwork..
>
> @all <https://github.com/all>
> I am confused with all this irrelevant talk of Joomla core translations
> btw - nothing to do with me or what I do elsewhere. All I was suggesting is
> that we modernise the whole workflow rather than use an old fashioned way
> of working or choose yet another method as every other joomla project seems
> to do.
>
> My contribution really was going to be in the actual en-GB language
> including grammar. In another life I do a lot of technical en-GB proof
> reading which has been, for the past 15 years, a great way to learn
> preciseness and remove ambiguity. If we are taking media style guides as
> our base, this isn't perhaps the kind of work you need to be done. I
> thought that this style guide was to clean up the en-GB in core rather than
> a general SG which would include content narrative and colloquial en-GB.
>
> So I will step down from this team. I do have strong views on my language
> and its use but working in this kind of team isn't going to be productive
> for me or this team.
>
> Good luck and well done for tackling this much needed area of Joomla.
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/29#issuecomment-72316192>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
If you have been following the commits you will have seen that I have moved all the docs to a new branch called gh-pages to enable publication.

You can see the current "draft" release of this documentation here http://joomla.github.io/user-interface-text/

Just need to polish up the introduction and order the menu and then its over to the PLT to publish a link on the developer.joomla.org web site.

The template used is exactly the same one as is used for the code style guide

**Comment by brianteeman** [comment]
The link has no been published on the devloper.joomla.org web site.
