### ISSUE TITLE
PROPOSAL workflow for approving PR in Joomla that effect language strings

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#30]
## Reason  
To avoid the issues that we have been working hard to resolve here from re-occurring we need a way for any PR that touches a string to be checked and approved by a member of this WG before it can be accepted. (Currently I try to watch all PR manually to see if they do but this is not sustainable and fails on the "Falling under a bus" rule.  

In addition the method used to notify Translation Teams of changes is very slow and outdated (they are emailed a diff) and also fails the "Falling under a bus" rule.  

### Prerequisites
* Create a bot that adds a label to any pull request with a change in a .ini file as **TH**
* Translation Hub website (**THS**) - in my head this is a fork of jtracker or another project on the issues.joomla.org website

### Workflow
* The **THS** automatically lists any PR with a label **TH**
* Any issue on **THS** has a status 
* When an issue is marked as approved on **THS** by a WG member then github automatically updated and label changed from **TH** to **TH-Yes**
* An issue on github with label **TH** can't be merged by the CMS maintainers it must have **TH-yes**
* Translation Teams can subscribe for notifications of entries at **THS** with status **TH-yes**
* The web site is also the home of the en-GB style guide and any translations

### Benefits
* Removes the need for one person to create a diff
* Removes the need for TT to wait for a diff before updating their translation
* Ensures that no bad strings are merged

**Comment by wilsonge** [comment]
I think the general principal is good. However My only concern is as this is currently a smallish WG if people are away (over holiday periods etc.) then it can hold up things getting merged whilst we wait for PR's to be approved by the WG.

**Comment by mbabker** [comment]
Prerequisites:

* The existing issue tracker bot and pull request listener can manage this.  A new task would be needed in the [CMS pull listener](https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php) which would parse the file list for a pull request and determine if a language file has been modified
* The issue tracker is designed for multi project support and does not have a requirement to be connected to GitHub.  The downside to having a non-GitHub based project in that application is there isn't a notification system built into it right now.

Workflow:
* The pull request listener can manage opening the issue on the THS tracker (whether it's built into our own issue tracker or any other system as long as there is a public facing REST API) as well as manage the merge status of the CMS pull request to flag it as "do not merge" (see https://github.com/joomla/joomla-cms/pull/2699 for an example) until designated otherwise.  Likewise, once the THS tracker item is flagged as approved, our issue tracker application can receive some sort of notification on the CMS project to update the corresponding pull request.

**Comment by brianteeman** [comment]
Regarding waiting

1. this is a small group but it is better than no group
2. we dont merge bad code so we shouldnt merge bad language strings either
3. this WG is not like any other WG - it reacts quickly. We dont have to
have endless meetings to make a decision
4. 99% of the time its just a quick read of the string to check it matches
to the style guide
5. If it is not already covered by the style guide then I suspect strongly
that the code is bigger than just a simple fix and is not exactly likely to
merged in a short period of time ayway - what is the average time from PR
to merge?

On 7 January 2015 at 14:22, George Wilson <notifications@github.com> wrote:

> I think the general principal is good. However My only concern is as this
> is currently a smallish WG if people are away (over holiday periods etc.)
> then it can hold up things getting merged whilst we wait for PR's to be
> approved by the WG.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/30#issuecomment-69027511>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
1. Yes I don't disagree
2. Tags :p 
3-5. Yes I don't disagree it should be fast. But for example over xmas I merged (and tested) an awful lot because I had time to put into it. For others at holiday period they have to (understandably) spend lots of time with family and drop the Joomla priorities back a bit. That's the way it goes. But I want to make sure that if that happens in this group it doesn't hold back the rest of the CMS

**Comment by brianteeman** [comment]
I would rather hold up the CMS and get it right than get back in to the
unholy mess we have now.

You dont merge code that has a missing tab so why merge code that has a
missing u

On 7 January 2015 at 14:45, George Wilson <notifications@github.com> wrote:

>
>    1. Yes I don't disagree
>    2. Tags :p 3-5. Yes I don't disagree it should be fast. But for
>    example over xmas I merged (and tested) an awful lot because I had time to
>    put into it. For others at holiday period they have to (understandably)
>    spend lots of time with family and drop the Joomla priorities back a bit.
>    That's the way it goes. But I want to make sure that if that happens in
>    this group it doesn't hold back the rest of the CMS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/30#issuecomment-69030625>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
> Translation Hub **web site** (THS) ...

Thought it is going to be **website**.

I'm a newbie to this. Is there a tutorial on how to contribute here?

**Comment by brianteeman** [comment]
Good spot ;)

As for contributing. If you have a topic you want to raise for discussion
just click on the New Issues button and type away.

On 7 January 2015 at 17:06, rgmears <notifications@github.com> wrote:

> Translation Hub *web site* (THS) ...
>
> Thought it is going to be *website*.
>
> I'm a newbie to this. Is there a tutorial on how to contribute here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/30#issuecomment-69054009>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
I thought that at some point the en-GB file(s) will be gone through line by line and corrected. Or is that something that will be taken care of by one person?

**Comment by brianteeman** [comment]
AH yes I see what you mean now.


*Global Issues*
So far I have applied all the changes that I can from the style guide and
am waiting for that to me merged in to core. This will be done before the
release of 3.4.

*Specific Issues *
We have already identified numerous issues that we want to address and each
one of them will have to be handled as an individual issues after the
release of 3.4

*More Detailed Review*
This has to be done screen by screen and not line by line so we can see the
text in context. Ideally I think it works well if we do this component by
component and if an issue is discovered an issue is created here t report
it. Then we can decide on the correct response/change to that issue and
make the changes.


On 7 January 2015 at 18:48, rgmears <notifications@github.com> wrote:

> I thought that at some point the en-GB file(s) will be gone through line
> by line and corrected. Or is that something that will be taken care of by
> one person?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/30#issuecomment-69070203>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
> Removes the need for TT to wait for a diff before updating their translation

Working on each small changes ('THS') brought to language files when it is done is not only unrealistic for Translation teams, but also undesirable.
The reason is simple: between that change and a release, the change could be reverted or changed again.
For recent examples :
I had translated some new plugins in 3.4.0-dev which we deleted since... loss of time.
en-GB.plg_user_session.ini
en-GB.plg_system_session.ini
en-GB.plg_system_session.sys.ini
en-GB.plg_user_session.sys.ini

Or the changed joomlaupdate strings, etc.

It is only when language is frozen that a .diff should be provided (TT can also use our specific modules to check their translations at that time vs what is in core without the provided .diff as they can use these modules themselves. But some have difficulties setting these modules, thus why we propose pdf)

**Comment by brianteeman** [comment]
No one is forcing a TT to use the system in this proposal
This has major advantages to ensure that translations are up to date as the
TT do not have to wait until a language freeze and have approximately 1
week to make all changes. With this method of notification they can if they
wish make changes as they are committed - a lot less work to do over time
than having to do it all at once

On 8 January 2015 at 09:07, infograf768 <notifications@github.com> wrote:

> Removes the need for TT to wait for a diff before updating their
> translation
>
> Working on each small changes ('THS') brought to language files when it is
> done is not only unrealistic for Translation teams, but also undesirable.
> The reason is simple: between that change and a release, the change could
> be reverted or changed again.
> For recent examples :
> I had translated some new plugins in 3.4.0-dev which we deleted since...
> loss of time.
> en-GB.plg_user_session.ini
> en-GB.plg_system_session.ini
> en-GB.plg_system_session.sys.ini
> en-GB.plg_user_session.sys.ini
>
> Or the changed joomlaupdate strings, etc.
>
> It is only when language is frozen that a .diff should be provided (TT can
> also use our specific modules to check their translations at that time vs
> what is in core without the provided .diff as they can use these modules
> themselves. But some have difficulties setting these modules, thus why we
> propose pdf)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/30#issuecomment-69153005>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
As I insisted above: <b>to make changes before freeze is idiotic for a TT</b> (even after freeze we may have to do some changes, which happens regularly).
Only a handful of TTs would subscribe and read these Notifications and in any case I will strongly suggest (to the recent coordinators, ancient volunteers know better...) that they do not change their files until freeze as we have been burnt more than once in the past.
I just gave some examples above...

**Comment by brianteeman** [comment]
I am glad to hear you speak for all TT without asking them.

**Comment by marijkestuivenberg** [comment]
Especially the idea to label PR's related to adding/changing language files or strings I do like. As already said the diff that is presented to the TTs after freeze is not an optimal way. Often I find myself wasting time to search for a specific item where things got changed to learn more about it. Finding them in one place or with a clear label would be very helpful.

Whether TTs start working on processing changes after freeze or not is up to them selves. A good advice is always welcome of course, but one can decide for them selves and plan their own volunteer time. I don't think this is an issue, and certainly not the subject in this matter.

**Comment by brianteeman** [comment]
@mbabker has created the code that adds a language label to any pull request with a change in a .ini file

**Comment by mbabker** [comment]
> Only a handful of TTs would subscribe and read these Notifications

Then let that handful use a workflow where they aren't waiting for someone to provide them the "official diff" to update their translations.  Those teams might be willing to deal with the frustration of strings changing multiple times between a release, or they may just watch the notifications to gauge the number of changes that are coming so they can plan the time needed to update for the next release more efficiently.

What I see here is expanding the workflow for translation management.  Right now, I see a single flow that is managed in a very explicit way.  Has it been working?  Yes.  Can it be better?  Always.  Let's not shoot down ideas if there's any merit in them and they may benefit some of those involved in the behind the scenes work.

**Comment by infograf768** [comment]
I welcome the addition of a language label.
