### ISSUE TITLE
Proposal : select

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#31]
Select: Use the word "select". Never: "click". Click refers to a mouse and is not relevant if using a tablet or a keyboard.

**Comment by brianteeman** [comment]
For example, to describe the use of a checkbox in your UI, tell the user to “select" the checkbox, not to "check,” “click,” or “turn on” the checkbox.

**Comment by Hils** [comment]
Agree with select. 

I have just researched 'check' as that is something I am comfortable using but of the many meanings in the (physical) Concise Oxford Dictionary, in en-GB it is wrong.

Select = choose.

**Comment by brianteeman** [comment]
check - biggest issue as identified by both apple and mozilla was you dont
check on your tablet

On 10 January 2015 at 13:03, Hils <notifications@github.com> wrote:

> Agree with select.
>
> I have just researched 'check' as that is something I am comfortable using
> but of the many meanings in the (physical) Concise Oxford Dictionary, in
> en-GB it is wrong.
>
> Select = choose.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/31#issuecomment-69455028>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hils** [comment]
Being pedantic, one might check on one's tablet but only to see if it was OK .

**Comment by brianteeman** [comment]
Exactly but that is a different meaning for check where it means select

On 10 January 2015 at 13:31, Hils <notifications@github.com> wrote:

> Being pedantic, one might check on one's tablet but only to see if it was
> OK .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/31#issuecomment-69455789>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
Select is good; maybe make it all caps: SELECT

**Comment by brianteeman** [comment]
Does this apply to buttons as well as select boxes?

![w vf](https://cloud.githubusercontent.com/assets/1296369/5756301/cb923be8-9ca5-11e4-8034-5f6bb55fc74a.png)

**Comment by brianteeman** [comment]
And what about a situation where there are two selections?

![n9rz](https://cloud.githubusercontent.com/assets/1296369/5756322/10629d76-9ca6-11e4-8169-bd36239f00bb.png)

**Comment by rgmears** [comment]
Yes and yes.

**Comment by brianteeman** [comment]
See https://github.com/joomla/joomla-cms/pull/7430
