### ISSUE TITLE
WANTED : Volunteer to draft an interface guideline doc

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#32]
In the [References](https://github.com/joomla/user-interface-text/blob/master/references.md) you will see a few short documents from Mozilla, Apple and Microsoft which outline some rules for the interface. For example Labels should be title case and Descriptions should be sentence case.

A lot of them do not apply to us as they are not specifically for web apps but we can take a lot from them. Would someone be willing to take these sources and prepare a draft  interface guideline doc.

**Comment by rgmears** [comment]
How is this different from what you are already putting together?

**Comment by brianteeman** [comment]
https://developer.mozilla.org/en-US/Apps/Design/Copy_styleguide

See the section Specific interface features

Its more a visual reference

On 10 January 2015 at 17:38, rgmears <notifications@github.com> wrote:

> How is this different from what you are already putting together?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/32#issuecomment-69464228>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
And where is the Joomla! specific material that requires massaging into the new style guide?

**Comment by brianteeman** [comment]
Any joomla screen. Think about taking the article manager view and the
article edit video as screenshots and then adding appropriate labels and to
each type of text. Eg title, button, option, tooltip, select ...

**Comment by rgmears** [comment]
So you want someone to make screenshots that match the guidelines?

**Comment by brianteeman** [comment]
annotated ones
