### ISSUE TITLE
Ascending in filters

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#34]
http://issues.joomla.org/tracker/joomla-cms/5657

Should filters be title case for consistency?

**Comment by Hils** [comment]
I have been thinking about this for a while and am uncomfortable with the amount of times we are using title case instead of sentence case. Headings, major ones eg h1 or h2 traditionally would be capitalised. I don't think it is modern practice.

An example rule from Cambridge University
http://www.cam.ac.uk/brand-resources/guidelines/editorial-style-guide
Others compromise with (say) a capitalised main header and sentence case for all others :
http://www.theaa.com/style/editorial/page-structure-and-heading-style.html .

Personally, I no longer use title case. I find it distracting, particularly in our Joomla files and what does it achieve?

I mention this now as yes, we should be consistent but consistent with what. Perhaps we should agree on the subject of case first?

**Comment by brianteeman** [comment]
Hadnt seen those links i will add them to the resources.

However we are talking about UI not content. They are not the same thing
Please read the UI resources in the references link. They all say Title
Case.

On 10 January 2015 at 13:28, Hils <notifications@github.com> wrote:

> I have been thinking about this for a while and am uncomfortable with the
> amount of times we are using title case instead of sentence case. Headings,
> major ones eg h1 or h2 traditionally would be capitalised. I don't think it
> is modern practice.
>
> An example rule from Cambridge University
> http://www.cam.ac.uk/brand-resources/guidelines/editorial-style-guide
> Others compromise with (say) a capitalised main header and sentence case
> for all others :
> http://www.theaa.com/style/editorial/page-structure-and-heading-style.html
> .
>
> Personally, I no longer use title case. I find it distracting,
> particularly in our Joomla files and what does it achieve?
>
> I mention this now as yes, we should be consistent but consistent with
> what. Perhaps we should agree on the subject of case first?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/34#issuecomment-69455695>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hils** [comment]
I will go back and read resources but I still want to question our (Joomla's) use of title case.
>Personally, I no longer use title case. I find it distracting, particularly in our Joomla files and what does it achieve?

That is a UI/UX comment.

**Comment by dw1Rianto** [comment]
Hi @Hils and @brianteeman 

Can I put a suggestion?  We can add CSS <code>text-transform: capitalize</code> to solve it. It'll take care of the case.

**Comment by brianteeman** [comment]
No thats no the right way to do this as it forces something that may not be
correct in other languages

**Comment by infograf768** [comment]
>No thats no the right way to do this as it forces something that may not be correct in other languages

Indeed. It is considered as very bad practice to capitalise common words inside a group of words in French.

**Comment by dw1Rianto** [comment]
>  as it forces something that may not be correct in other languages
>> very bad practice to capitalise common words inside a group of words in French.

Yes, you're right. Thanks for the enlightenment. UI on a system should achieve its solidity too. I'll go for 'yes' button for consistency. ding!

**Comment by horus68** [comment]
Yes for consistence. Just remember each language has its own rules! In Portuguese we do not use ALL CAPS or "Title case" but sentence case. Title case as a strict use (People and company names, Places). Also: month and day names are now not capitalized for us!

**Comment by brianteeman** [comment]
Having looked at both the firefox os and the microsoft design guidelines it looks ok to use sentence case in dropdown lists
