### ISSUE TITLE
Submit versus send

### ISSUE THREAD

**Issue by rgmears** [joomla/user-interface-text#35]
Some forms use SUBMIT. Others use SEND.

I think SEND is better.

**Comment by brianteeman** [comment]
Really?

You would send an email on a contact form but you would submit the data on a tax return form. Here it is all about the context - not a global setting

**Comment by rgmears** [comment]
Either way you are sending information. However, I see your point.

**Comment by brianteeman** [comment]
I just took a fresh look at this and from what I could see I only found Send when it referred to mail and Submit when it referred to data. Is there somewhere that I missed?
