### ISSUE TITLE
Proposal Content Module Names - rename 

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#36]
* Archived Articles  
* Articles - Newsflash
* Articles - Related Articles   
* Articles Categories  
* Articles Category  
* Latest News
* Most Read Content

I think it would be better and more consistent if we renamed them as below and this will mean that they are all grouped together in the list of available modules

* Articles - Archived
* Articles - Newsflash  
* Articles - Related Articles   
* Articles - Categories  
* Articles - Category  
* Articles - Latest
* Articles - Most Read Content

**Comment by rgmears** [comment]
>  Articles - Archived
  >  Articles - Newsflash
   > Articles - Related Articles
   > Articles - Categories
   > Articles - Category
   > Articles - Latest
   > Articles - Most Read Content

Would make it even simpler:

* Articles - Archived
* Articles - Newsflash
* Articles - Related
* Articles - Categories
* Articles - Category
* Articles - Latest
* Articles - Most Read

**Comment by Hils** [comment]
>this will mean that they are all grouped together

@brianteeman  good idea

Simplification of labels @rgmears - I can't see anything against this.

**Comment by brianteeman** [comment]
Thanks - submitted with @rgmears suggestions https://github.com/joomla/joomla-cms/pull/5725
