### ISSUE TITLE
Proposal Tag Module names - rename

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#37]
* Popular Tags
* Similar Tags

I think it would be better and more consistent if we renamed them as below (similar to the Articles proposal) and this will mean that they are all grouped together in the list of available modules

* Tags - Popular
* Tags - Similar

**Comment by rgmears** [comment]
agree

**Comment by Hils** [comment]
yes - consistent with article mod names.

**Comment by brianteeman** [comment]
Thanks - PR submitted https://github.com/joomla/joomla-cms/pull/5725
