### ISSUE TITLE
Tooltips on icons in list views

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#38]
If you look at the icons in list views such as article manager you will see they are a mix of descriptions and actions. The icons themselves can be both informative of the state and descriptive of their action.

We need to review these and make some sort of consistent standard

![dcv7](https://cloud.githubusercontent.com/assets/1296369/5755946/2c14e082-9ca2-11e4-9ef7-d90ac98730da.png)

![dcv7 1](https://cloud.githubusercontent.com/assets/1296369/5755955/383d1046-9ca2-11e4-9d1c-d13ea7acd18d.png)

![slu](https://cloud.githubusercontent.com/assets/1296369/5755958/46722796-9ca2-11e4-859e-ca4a36dbab11.png)

**Comment by JoomliC** [comment]
Does we really need here the start date of publishing ?

Maybe something like this in replacement (it's just my suggestion, which could be improved ;-) ): 
<blockquote>Published and is Current
Click to unpublish</blockquote>

<blockquote>Trashed Item
Click to Publish</blockquote>

<blockquote>Archived Item
Click to Unpublish</blockquote>

**Comment by wilsonge** [comment]
The start date of publishing would be down to the UI group not this one.

**Comment by brianteeman** [comment]
This is just to standardise on the strings used to make sure they are
correct and consistant

On 15 January 2015 at 13:45, George Wilson <notifications@github.com> wrote:

> The start date of publishing would be down to the UI group not this one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/38#issuecomment-70087004>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by JoomliC** [comment]
<blockquote>
The start date of publishing would be down to the UI group not this one.
</blockquote>
@wilsonge Oh sorry, i followed a link from a PR, and had not enough attention of where i arrived... :-|

**Comment by rgmears** [comment]
Regardless the content, the text size should be increased. Or the colours switched. Tiny white text on a black background is difficult to read.

**Comment by brianteeman** [comment]
I agree with you @rgmears as my aged eye sight finds it almost impossible to read many of them but sadly @wilsonge seems to be saying we cant touch it as the imaginary UI group has to do that.

I see no harm at all in discussing it here OR for a PR to be created and submitted just as anyone can submit a PR.

BUT for the purpose of this Issue here lets try to resolve the best way to handle the strings so that they are consistent and meaningful.

**Comment by wilsonge** [comment]
Awesome :) Thanks guys!

**Comment by rgmears** [comment]
Where does one go to submit/add/contribute/posit a PR in this regard?

**Comment by brianteeman** [comment]
issues.joomla.org

On 16 January 2015 at 02:55, rgmears <notifications@github.com> wrote:

> Where does one go to submit/add/contribute/posit a PR in this regard?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/38#issuecomment-70201366>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
Started here: [#5957] (http://issues.joomla.org/tracker/joomla-cms/5957)
Not sure how or where to include the altered CSS.

**Comment by brianteeman** [comment]
First of all I would make sure you include your comment or no one will understand the reasoning behind the change and that it is not just cosmetic

> Regardless the content, the text size should be increased. Or the colours switched. Tiny white text on a black background is difficult to read.

Secondly your css changes should be in media/jui/bootstrap.css
(someone will probably tell you to make them in LESS as well but this should be enough for the review stage

This may help you as well http://www.joomla-css.nl/en/styling-joomla-3-content-components/tooltip

**Comment by rgmears** [comment]
To make the screenshot I used the CSS in the template.css file for the ISIS template where it appears to be a duplication of bootstrap.css.

Actually, the various LESS and CSS files have tooltips all over the place both in JUI and templates.

**Comment by rgmears** [comment]
Thanks Brian. I use a desktop compiler. (Still working in Windows.)

**Comment by zero-24** [comment]
@rgmears 

Have you any local server e.g. xampp?

You can use a batch like this:
```batch
@echo off
echo Start generatecss.php
echo Generate Joomla CSS from the LESS Files
X:\PATH\TO\XAMPP\php\php.exe X:\PATH\TO\XAMPP\htdocs\FOLDER\build\generatecss.php
echo All ok!
pause
```

Please replace
`X:\PATH\TO\XAMPP` with your path to the xampp directory
and
`FOLDER` with your folder namen at the htdocs folder

so copy the script with the changes into a file that call like: `cmd_php_generatecss.bat` and execute it per double click on it.

Than it open a CMD that run the command and ends with the message `All ok!` so now you can commit it :smile: I hope it helps.

**Comment by rgmears** [comment]
Yes, I am using XAMPP. It's not a big deal to use a DT Compiler. I will simply make copies of the originals (in Notepad ++) and then make the changes. For doing a PR do I not simply upload the changed files to GitHUb? Which in this case would be 4 files: two for each template: the template/less/tooltip.less and template/css/template.css
