### ISSUE TITLE
Sticky 

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#39]
in the banner manager we have a horrible term Sticky. Its particularly horrible as the negative is usticky which I am pretty sure is not a word

Would it be better to replace sticky/unsticky with pinned/unpinned

** example one **
COM_BANNERS_FIELD_STICKY_DESC="Whether or not the Banner is 'sticky'. If one or more Banners in a Category are sticky, they will take priority over Banners that are not sticky. For example, if two Banners in a Category are sticky and a third Banner is not sticky, the third Banner will not display if the module setting is 'Sticky, Randomise'. Only the two sticky Banners will display."

==>

COM_BANNERS_FIELD_STICKY_DESC="Whether or not the Banner is 'pinned'. If one or more Banners in a Category are pinned, they will take priority over Banners that are not pinned. For example, if two Banners in a Category are pinned and a third Banner is not pinned, the third Banner will not display if the module setting is 'Pinned, Randomise'. Only the two pinned Banners will display."

** example two ** 
COM_BANNERS_N_BANNERS_STUCK="%d banners successfully stickied."
COM_BANNERS_N_BANNERS_UNSTUCK_1="%d banner successfully unstickied."

==>
COM_BANNERS_N_BANNERS_STUCK="%d banners successfully pinned."
COM_BANNERS_N_BANNERS_UNSTUCK_1="%d banner successfully unpinned."

**Comment by chrisdavenport** [comment]
Definite improvement in my opinion.

**Comment by brianteeman** [comment]
Thats good enough for me - PR submitted

https://github.com/joomla/joomla-cms/pull/5857

On 21 January 2015 at 20:06, Chris Davenport <notifications@github.com>
wrote:

> Definite improvement in my opinion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/39#issuecomment-70911408>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hutchy68** [comment]
Yes, big improvement.

**Comment by brianteeman** [comment]
If you guys can do a quick test of the PR then we can get this one merged
