### ISSUE TITLE
Category Manager

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#40]
This issue was raised on the general tracker by @MartijnMaandag and I said we would look at it

Yes I do understand now what the intention is.
The banners helped me to understand. They are better as the Articles, but still confusing because there is no Category Manager.
I do suggest the following:
Change the Banners - Categories from 
**Category Manager: Banners**
Into
**Banner Manager: Categories**
This way the Categories inside Banners have the same heading as Banners, Clients and Tracks.
For Contacts, Newsfeeds and Web Links  the same;-)
And the Articles?
I did attach an example where the structure is the same as Banners. Change the header from
**Category Manager: Articles**
into
**Article Manager: Categories**
![screen shot 2015-01-22 at 04 45 17](http://issues.joomla.org/uploads/1/ae3c406ea08d129d5a294737813142b5.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5853">issues.joomla.org/joomla-cms/5853</a>.</sub>

**Comment by rgmears** [comment]
I think it's better to go the other way: Make Content the same as Banners. Your approach adds a third level to get to Add New Article.

**Comment by brianteeman** [comment]
Not my approach I just copy/paste the original report

**Comment by rgmears** [comment]
Okay. The approach presented, then.

While we're on the subject I think the word Manager should be dropped from all of the various uses of it. It's redundant. Perhaps this should be a new issue?

**Comment by brianteeman** [comment]
I absolutely agree with you on the word Manager. I thought I had created n issue for it but looks like i didnt - can you.

**Comment by rgmears** [comment]
Done: https://github.com/joomla/user-interface-text/issues/42

**Comment by MartijnMaandag** [comment]
I am on holiday now. I will answer at the end of next month.

**Comment by brianteeman** [comment]
Closing this in favour of the more general #42
