### ISSUE TITLE
can't, cannot and can not

### ISSUE THREAD

**Issue by Hils** [joomla/user-interface-text#41]
We did discuss this before and I suggested can not was no longer used. Some notes:

"the OED says that the one-word construct cannot is "the ordinary modern way of writing can not" with a space between it, which apparently is archaic, or non-modern, or some such. –  tchrist Aug 20 '12 at 19:22 

Stylistically, the choice between can't and cannot is more complex. Generally, people use can't in speech and informal writing, and cannot or can not in formal writing or very formal speech."

http://english.stackexchange.com/questions/78935/when-to-use-cannot-versus-cant

Most references agree that can't and cannot are interchangeable depending on the level of formality. So - what level of formality should we be using? Are we supposed to be adding some chatty text or formal information?

**Comment by brianteeman** [comment]
https://github.com/joomla/user-interface-text/blob/master/A-Z.md#contractions

taken from https://www.gov.uk/guidance/content-design/writing-for-gov-uk#contractions



Personally I prefer the more modern can't. Can not and cannot are not interchangeable and it is much easier to avoid mistakes if we use this contraction. While I agree some contractions are not to be used I find that can't is acceptable.

**Comment by Hils** [comment]
OK - I made my point. The difference between can't and cannot is formality not archaicness (I made that word up probably) so if you have decided that you want the strings to be less formal we should apply that decision to all. My personal vote is to keep it more formal which tends to stop ambiguity.

Noting that your quote could be read several ways "Use contractions sparingly eg can't."

**Comment by rgmears** [comment]
I agree with @Hils
> My personal vote is to keep it more formal which tends to stop ambiguity.

**Comment by brianteeman** [comment]
There are very very few sources available to guide on this stuff. My preference is that where an authorarive enGB source exists such as the UK government that we use that.

**Comment by Hils** [comment]
Brian - I thought we were working as a team.

I think we should remember also that we are discussing narrative attached to code. Preciseness is really important in this context particularly as it is also the basis for translation.

**Comment by brianteeman** [comment]
On 23 Jan 2015 19:49, "Hils" <notifications@github.com> wrote:
>
> Brian - I thought we were working as a team.
>

Me too - I've been asking for contributions and reviews.

> I think we should remember also that we are discussing narrative attached
to code. Preciseness is really important in this context particularly as it
is also the basis for translation.
>

Yes thats one of the reasons I prefer using can't and not potentially
having cannot and can not which are not the same.

**Comment by rgmears** [comment]
cannot and can not mean the same thing do they not?

**Comment by brianteeman** [comment]
1) you can not only do this, but you can also do this …

2) you cannot only do this, but you can also do this…

The first means something, the second is gibberish

**Comment by rgmears** [comment]
> the second is gibberish

No it's not.

You cannot call something gibberish when it makes perfect sense to most readers. Like many words in English that are pairs repeated over and over &mdash; web site &gt; website &mdash; can not has been joined into cannot.

**Comment by chrisdavenport** [comment]
"you can not only do this, but you can also do something else…", whilst techically correct is only used to place emphasis on the "not only" and I would suggest that the entire sentence should be rewritten to avoid it, especially given that translators might easily miss the subtelty.  For example, I would rewrite it as "not only can you do this, but you can also do something else...", or perhaps even better would be "You can do something else, but you can also do this...".

So, if we eliminate "can not", then it's just a choice between "cannot" and "can't".  Both are correct and both would be acceptable, but the former has a slightly more formal tone to it.  So, I think it comes down to deciding whether the tone of the language strings should err on the formal or informal side of neutrality and that is a more general decision than just "cannot/can't".  If we decide to go formal then we would need to prefer "would not" to "wouldn't" and "should not" to "shouldn't" and so on.

My personal opinion is that the gov.uk argument that "Sometimes, lots of ‘cannot’, ‘should not’ etc can seem archaic and formal. That’s a tone we can move away from without jeopardising the overall tone of information coming from government." is likely to ring true for the majority of websites and so I think we should go with the less formal contractions.
