### ISSUE TITLE
Volunteer.joomla.org

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#45]
Please dont forget to add yourself to http://volunteers.joomla.org/ and I can add you to the list of group members

**Comment by rgmears** [comment]
@brianteeman

I have an account on the Joomla Forum but I cannot log in with that name on the page you linked to. Do I have to set up another Joomla account?

**Comment by brianteeman** [comment]
Yes. The Joomla sites do not share logins

**Comment by rgmears** [comment]
Done.

**Comment by brianteeman** [comment]
Added you

**Comment by rgmears** [comment]
Thanks.
