### ISSUE TITLE
Directory or Folder

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#52]
Its a mess. We use both terms and really we should standardise on one. We even use both terms on the same page.

![joomla web installer](https://cloud.githubusercontent.com/assets/1296369/8773037/137743ee-2ec9-11e5-8421-25f8b75206ac.png)

Or use folder on one screen and directory on another when referring to the same thing

![dir1](https://cloud.githubusercontent.com/assets/1296369/8773126/bd78ecda-2ec9-11e5-83b7-57d79ad9bf86.png)

![dir2](https://cloud.githubusercontent.com/assets/1296369/8773129/c069a808-2ec9-11e5-879d-084d2f155c53.png)

My personal preference is for directory

**Comment by wilsonge** [comment]
When you're in Windows you create "Folders" and they are called "Folder Directories". So I'd go with folders personally

**Comment by brianteeman** [comment]
For reference we currently have 
Folder: 192 
Directory: 184

**Comment by brianteeman** [comment]
@wilsonge strictly speaking a directory refers to a physical place in the filesystem whereas a folder could be a virtual one (think printer folder on windows)

http://stackoverflow.com/questions/5078676/what-is-the-difference-between-a-directory-and-a-folder

**Comment by brianteeman** [comment]
Further reading 
http://stackoverflow.com/questions/1191381/english-ui-terminology-directory-or-folder/1195096#1195096

**Comment by MAT978** [comment]
I won't be the Frenchy who will tell you how you should do, *but* in the FR current language, a directory (répertoire) or folder (dossier) mean the same thing.
The only thing is that the directory gives the "illusion" of a larger container. Then you can place a folder inside a directory but not the opposite. This is the way **they are understood**, not necessarily the correct.
Don't know if this can help but anyway... +:100: for "we should standardise on one"

**Comment by Hils** [comment]
I put my images in the image folder - you did state that there are still 180+ instances of directory. But more than that - cPanel uses folders and files:
![joomla-cpanel](https://cloud.githubusercontent.com/assets/736887/8801676/4bc10cb2-2fb4-11e5-8baa-0cadc75121a0.PNG)

**Comment by brianteeman** [comment]
lets go with cpanel then and use folder - I guess I am just old school and
still think of the CLI where it is definitely a directory.

At the end of the day consistency is more important than anything else

On 21 July 2015 at 14:25, Hils <notifications@github.com> wrote:

> I put my images in the image folder - you did state that there are still
> 180+ instances of directory. But more than that - cPanel uses folders and
> files:
> [image: joomla-cpanel]
> <https://cloud.githubusercontent.com/assets/736887/8801676/4bc10cb2-2fb4-11e5-8baa-0cadc75121a0.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/52#issuecomment-123303253>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Do we also change directory to folder in the following example cases

COM_ADMIN_LOG_DIRECTORY="(Log directory)"
COM_ADMIN_DIRECTORY_PERMISSIONS="Directory Permissions"
COM_CONFIG_FIELD_FTP_ROOT_DESC="The path to the root directory of the FTP server. The root directory is the base directory to which the FTP server is allowed access."

**Comment by brianteeman** [comment]
PR submitted - please test https://github.com/joomla/joomla-cms/pull/7523
