### ISSUE TITLE
for a specific menu item OR by the menu settings

### ISSUE THREAD

**Issue by cyrezdev** [joomla/user-interface-text#55]
After looking at com_content global options, to check some en-GB translations, i was stucked by the tabs description (fieldsets).
As the descriptions for each tabs are mixed of 2 different sentence constructions, i wonder which one is better to use, and if this should be checked, and unified ?

<code>version 1</code> ... unless they are changed <b>for a specific menu item.</b>
OR
<code>version 2</code> ... unless they are changed <b>by the menu settings.</b> ?

Examples : 
- <code>Articles</code> <code>version 1</code> These settings apply for article layouts unless they are changed for a specific menu item.
- <code>Category</code> <code>version 2</code> These settings apply for Articles Category Options unless they are changed by the individual category or menu settings.
- <code>Categories</code> <code>version 2</code> These settings apply for Articles Categories Options, unless they are changed by the individual category or menu settings.
- <code>Blog/Featured Layouts</code> <code>version 1</code> These settings apply for blog or featured layouts unless they are changed for a specific menu item.
- <code>List Layouts</code> <code>version 1</code> These settings apply for List Layouts Options unless they are changed for a specific menu item or category.
- <code>Shared</code> <code>version 2</code> These settings apply for Shared Options in List, Blog and Featured unless they are changed by the menu settings.

Or is it normal ?

In other Joomla core components, it seems that <code>version 1</code> is the commonly used version...

Thank you!
Cyril

**Comment by HLeithner** [comment]
I'm closing this because the repo gets closed and the guilde has been moved to manual.joomla.org
