### ISSUE TITLE
Singular or Plural

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#56]
If you look at com_content you will see that we have the plural for the list view which is correct but when we new/edit/view an article it is also a plural and it probably should be a singular. The same is true for most but not all other components - is it it worth fixing this?

![articles](https://cloud.githubusercontent.com/assets/1296369/14738856/e1b255dc-087b-11e6-9924-e688c5ad9b41.png)

**Comment by wilsonge** [comment]
Just standardise the current singular ones on plural I think if plural is the majority. I think we can justify it being COMPONENT (special case for com_content): TASK (task omitted for list view). It's not in the current format with the semi-colon actually saying edit an article etc.

**Comment by RCheesley** [comment]
I guess it depends what it is referring to, whether it's referring to the item you are working with (hence singular) or the type of items (hence plural).

I think I would expect it to be referencing the item I'm working with, hence singular, when on new/edit and the type (hence plural) when in list view.

**Comment by chrisdavenport** [comment]
I'm sure it used to be singular (for the edit and new screens) on earlier versions of Joomla.  Looks like a regression to me.

**Comment by brianteeman** [comment]
Its kind of a regression - before we (I) removed the word manager the strings were

> COM_CONTENT_PAGE_ADD_ARTICLE="Article Manager: Add New Article"
COM_CONTENT_PAGE_EDIT_ARTICLE="Article Manager: Edit Article"
COM_CONTENT_PAGE_VIEW_ARTICLE="Article Manager: View Article"

and now they are

> COM_CONTENT_PAGE_ADD_ARTICLE="Articles: New"
COM_CONTENT_PAGE_EDIT_ARTICLE="Articles: Edit"
COM_CONTENT_PAGE_VIEW_ARTICLE="Articles: View"

**Comment by brianteeman** [comment]
I dont mind doing the work just not prepared for the aggro

**Comment by wilsonge** [comment]
I honestly think (or at least have persuaded myself) with the setup we have now it should be the plural. If we were going to have it as "Edit an Article" of course it should be singular. But the way it is with the semicolon it implies it's the resource type rather than the actual entity

**Comment by rgmears** [comment]
Singular is more appropriate @brianteeman 
And, if you're going to make the change then perhaps:

New Article
Edit Article
View Article

Reads better.

**Comment by rgmears** [comment]
On second thought what @wilsonge says is correct, too. 

However, on the Modules page it says:
Module: [mod_type]

on the Contacts page it says:
Contacts: New
...
Banners: New 
...
Web Link: New
...
News Feeds: New

Should be consistent either way.

**Comment by brianteeman** [comment]
Modules, plugins and templates are a slightly special case as we need to
display the subgroup as well eg Module-Menu or Module-Custom

**Comment by rgmears** [comment]
But Web Link is the same as the others.
