### ISSUE TITLE
Stats plugin

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#59]
In the new stats plugin there are three modes
Always Send - obvious function
Never Send - obvious function
and
On Demand - ???

If you chose On Demand what actually happens is that the info box that you had on every page asking if you want to send the stats reappears. So its not really "On Demand" but something like "Reset" or "Ask again"

Have I misunderstood what "On demand" does?

Anyone got an idea for a better, more accurate option name?

**Comment by rgmears** [comment]
Where is the "new stats plugin"?

**Comment by zero-24** [comment]
@brianteeman something like `Allways ask` or `Ask allways`?

**Comment by rgmears** [comment]
@brianteeman I've done as you request -- select "On Demand" -- but I cannot find "the info box on every page".

**Comment by Bakual** [comment]
I think it only reappears if you had the plugin disabled before and never clicked any option on the info box. But not sure either :smile:

**Comment by rgmears** [comment]
@Bakual I had the option "Always send" selected. Selecting "On demand" causes no change. Neither does selecting "Never send" and then "On demand". No info box anywhere.

**Comment by brianteeman** [comment]
So the question is - what is this option supposed to do? Only when we know what it supposed to be doing can we give it the correct text

**Comment by Bakual** [comment]
Looking at the code, it probably should be the "send once" option.

**Comment by brianteeman** [comment]
So is it a bug then that when i select that the info box reappears?

**Comment by Bakual** [comment]
Hard to say, the code isn't the simplest to read imho.
But the modes are internally called "Always", "Once" and "Never". See https://github.com/joomla/joomla-cms/blob/staging/plugins/system/stats/stats.php#L21-L36

Maybe if there were never any stats sent, then the box reappears but when there were already some stats sent, then the box doesn't show?

**Comment by brianteeman** [comment]
Yeah I tried to read the code to work it out but failed to see what happens
in code when "once" is selected

On 29 April 2016 at 20:31, Thomas Hunziker <notifications@github.com> wrote:

> Hard to say, the code isn't the simplest to read imho.
> But the modes are internally called "Always", "Once" and "Never". See
> https://github.com/joomla/joomla-cms/blob/staging/plugins/system/stats/stats.php#L21-L36
>
> Maybe if there were never any stats sent, then the box reappears but when
> there were already some stats sent, then the box doesn't show?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/59#issuecomment-215856179>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
> Yeah I tried to read the code to work it out but failed to see what happens
in code when "once" is selected

When you select "Once" in the message box, the stats are sent directly in the same method that sets the param (`onAjaxSendOnce`), see https://github.com/joomla/joomla-cms/blob/staging/plugins/system/stats/stats.php#L186. That's why you don't see it anyhwere else.

I think the code will not do anything when "On Demand" is selected.
If there was never some stats sent, then it's kind of a "reset" and shows the message box? It's confusing for sure.

**Comment by brianteeman** [comment]
Definitely needs some improvement

On 29 April 2016 at 20:58, Thomas Hunziker <notifications@github.com> wrote:

> Yeah I tried to read the code to work it out but failed to see what happens
> in code when "once" is selected
>
> When you select "Once" in the message box, the stats are sent directly in
> the same method that sets the param (onAjaxSendOnce), see
> https://github.com/joomla/joomla-cms/blob/staging/plugins/system/stats/stats.php#L186.
> That's why you don't see it anyhwere else.
>
> I think the code will not do anything when "On Demand" is selected.
> If there was never some stats sent, then it's kind of a "reset" and shows
> the message box? It's confusing for sure.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/user-interface-text/issues/59#issuecomment-215863394>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
I suppose, too, the question is what do you (Joomla) want it to do?
