### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ceford** [joomla/user-interface-text#69]
Most of the links are broken on this page: 

https://developer.joomla.org/en-gb-user-interface-text-guidelines/references.html

**Comment by brianteeman** [comment]
That;s not very helpful - which ones are broken. I think I found three

**Comment by brianteeman** [comment]
#70

**Comment by ceford** [comment]
> That;s not very helpful - which ones are broken. I think I found three

True! Sorry about that. I was doing something else (and watching football with the other eye) so thought I would mention it in passing. As this is only the second issue raised in this repo and the first was years ago I did not expect a reply. 

Some of the links (to newspapers) are too cluttered with prompts to subscribe and adverts to be readable. I think we need a few really good references rather than many irritating ones. Perhaps this: https://developers.google.com/style

I don't propose to do a PR myself. Too much else going on.

**Comment by brianteeman** [comment]
all the links have been updated correctly now.

**Comment by ceford** [comment]
Thank you!

**Comment by HLeithner** [comment]
Moved to manual.joomlüa.org
