### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#8]
Currently we have an inconsistency that 7 times we use Login Name - this is wrong we should always use Username.

On some other systems it might be that the two are different but not in Joomla - they are the same so we should only use one term.

"Log in with your Username"

Example  
`COM_USERS_USER_FIELD_USERNAME_LABEL="Login Name"`

Crazy Example  
`COM_USERS_USER_FIELD_USERNAME_DESC="Enter the login name (Username) for the user."`

**Comment by vdrover** [comment]
"Log in" or "Login"?

**Comment by brianteeman** [comment]
See https://github.com/joomla/user-interface-text/blob/master/Action%20or%20description.md

**Comment by Hutchy68** [comment]
Agree we should always use the word Username. Putting the term in parentheses to guide the meaning should not be required if the phrase is well written.

**Comment by Hils** [comment]
definitely agree! That doc link is looking really good Brian, btw.

**Comment by hdouglassmith** [comment]
Agree

**Comment by rgmears** [comment]
Username

**Comment by brianteeman** [comment]
OK I will update the styleguide and lang strings to remove Login Name and make sure it is documented so people know to not use that in the future
